---
driver:
  name: vagrant

provisioner:
  name: chef_solo

verifier:
  name: inspec
  sudo: true

platforms:
  - name: centos-7.1
  - name: centos-6.7
  - name: centos-5.11
  - name: debian-6.0.10
  - name: debian-7.8
  - name: debian-8.1
  - name: fedora-21
  - name: fedora-22
  - name: freebsd-9.3
  - name: freebsd-10.2
  - name: opensuse-13.2-x86_64
  - name: ubuntu-14.04
  - name: ubuntu-12.04
  - name: ubuntu-10.04
  - name: mint-17.2-cinnamon
    driver_config:
      box: artem-sidorenko/mint-17.2-cinnamon
  - name: windows-2008r2
    driver_config:
      box: opentable/win-2008r2-standard-amd64-nocm
  - name: windows-2012r2
    driver_config:
      box: opentable/win-2012r2-standard-amd64-nocm

suites:
  - name: default
    run_list:
      - recipe[os_prepare]
    attributes:
